version: '2'

services:

  orderer.bankingfederation.com:
    container_name: orderer.bankingfederation.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/bankingfederation.com/orderers/orderer.bankingfederation.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/bankingfederation.com/orderers/orderer.bankingfederation.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.partnersbank.bankingfederation.com:
    container_name: peer0.partnersbank.bankingfederation.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.partnersbank.bankingfederation.com
      - CORE_PEER_ADDRESS=peer0.partnersbank.bankingfederation.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.partnersbank.bankingfederation.com:7051
      - CORE_PEER_LOCALMSPID=PartnersBankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/partnersbank.bankingfederation.com/peers/peer0.partnersbank.bankingfederation.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/partnersbank.bankingfederation.com/peers/peer0.partnersbank.bankingfederation.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.partnersbank.bankingfederation.com:
    container_name: peer1.partnersbank.bankingfederation.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.partnersbank.bankingfederation.com
      - CORE_PEER_ADDRESS=peer1.partnersbank.bankingfederation.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.partnersbank.bankingfederation.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.partnersbank.bankingfederation.com:7051
      - CORE_PEER_LOCALMSPID=PartnersBankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/partnersbank.bankingfederation.com/peers/peer1.partnersbank.bankingfederation.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/partnersbank.bankingfederation.com/peers/peer1.partnersbank.bankingfederation.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer0.multibankwest.bankingfederation.com:
    container_name: peer0.multibankwest.bankingfederation.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.multibankwest.bankingfederation.com
      - CORE_PEER_ADDRESS=peer0.multibankwest.bankingfederation.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.multibankwest.bankingfederation.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.multibankwest.bankingfederation.com:7051
      - CORE_PEER_LOCALMSPID=MultiBankWestMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/multibankwest.bankingfederation.com/peers/peer0.multibankwest.bankingfederation.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/multibankwest.bankingfederation.com/peers/peer0.multibankwest.bankingfederation.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer1.multibankwest.bankingfederation.com:
    container_name: peer1.multibankwest.bankingfederation.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.multibankwest.bankingfederation.com
      - CORE_PEER_ADDRESS=peer1.multibankwest.bankingfederation.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.multibankwest.bankingfederation.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.multibankwest.bankingfederation.com:7051
      - CORE_PEER_LOCALMSPID=MultiBankWestMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/multibankwest.bankingfederation.com/peers/peer1.multibankwest.bankingfederation.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/multibankwest.bankingfederation.com/peers/peer1.multibankwest.bankingfederation.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
